import type {
  Application,
  Candidate,
  Department,
  Interview,
  Job,
  MatchScore,
  PipelineStage,
  RecruiterAlert,
  RecruiterMetric,
  ScreeningSession,
} from './types';

export const departments = [
  'Manufacturing',
  'Sales',
  'Supply Chain',
  'Finance',
  'Information Technology',
  'Research and Development',
  'Maintenance',
  'Marketing',
] satisfies Department[];

export const pipelineStages = [
  'sourced',
  'ai_matched',
  'screening_pending',
  'screened',
  'shortlisted',
  'interview_scheduled',
  'offer_final',
  'rejected',
] satisfies PipelineStage[];

export const recruiterMetrics = [
  {
    id: 'metric-open-jobs',
    label: 'Open jobs',
    value: 8,
    changePercent: 14,
    trend: 'up',
    description: 'Active hiring mandates across manufacturing and commercial teams.',
  },
  {
    id: 'metric-active-candidates',
    label: 'Active candidates',
    value: 128,
    changePercent: 9,
    trend: 'up',
    description: 'Candidates currently moving through recruiter-owned stages.',
  },
  {
    id: 'metric-screenings-due',
    label: 'Screenings due',
    value: 18,
    changePercent: -6,
    trend: 'down',
    description: 'Screening sessions waiting for recruiter action this week.',
  },
  {
    id: 'metric-interviews',
    label: 'Interviews scheduled',
    value: 11,
    changePercent: 0,
    trend: 'flat',
    description: 'Confirmed interviews across technical, functional, and HR rounds.',
  },
] satisfies RecruiterMetric[];

export const jobs = [
  {
    id: 'job-production-engineer',
    title: 'Production Engineer',
    department: 'Manufacturing',
    location: 'Pune, Maharashtra',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 3,
    candidatesCount: 24,
    shortlistedCount: 6,
    experienceMin: 3,
    experienceMax: 7,
    requiredSkills: ['Lean Manufacturing', 'Line Balancing', 'Root Cause Analysis', 'OEE'],
    preferredSkills: ['Six Sigma Green Belt', 'SAP PP', 'Kaizen'],
    createdAt: '2026-05-04T09:30:00.000Z',
  },
  {
    id: 'job-sales-manager-b2b',
    title: 'Sales Manager B2B',
    department: 'Sales',
    location: 'Mumbai, Maharashtra',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 2,
    candidatesCount: 19,
    shortlistedCount: 5,
    experienceMin: 6,
    experienceMax: 10,
    requiredSkills: ['B2B Sales', 'Dealer Management', 'Key Accounts', 'Negotiation'],
    preferredSkills: ['Industrial Products', 'CRM Forecasting', 'Channel Expansion'],
    createdAt: '2026-05-06T06:45:00.000Z',
  },
  {
    id: 'job-supply-chain-lead',
    title: 'Supply Chain Lead',
    department: 'Supply Chain',
    location: 'Chakan, Maharashtra',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 1,
    candidatesCount: 17,
    shortlistedCount: 4,
    experienceMin: 7,
    experienceMax: 12,
    requiredSkills: ['Demand Planning', 'Vendor Management', 'Inventory Control', 'S&OP'],
    preferredSkills: ['SAP MM', 'Import Documentation', 'Cost Optimization'],
    createdAt: '2026-05-08T11:10:00.000Z',
  },
  {
    id: 'job-finance-controller',
    title: 'Finance Controller',
    department: 'Finance',
    location: 'Bengaluru, Karnataka',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 1,
    candidatesCount: 13,
    shortlistedCount: 3,
    experienceMin: 10,
    experienceMax: 15,
    requiredSkills: ['Plant Finance', 'Budgeting', 'Cost Accounting', 'Internal Controls'],
    preferredSkills: ['IFRS', 'SAP FICO', 'Manufacturing Audit'],
    createdAt: '2026-05-10T04:15:00.000Z',
  },
  {
    id: 'job-maintenance-head',
    title: 'Maintenance Head',
    department: 'Maintenance',
    location: 'Aurangabad, Maharashtra',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 1,
    candidatesCount: 15,
    shortlistedCount: 4,
    experienceMin: 12,
    experienceMax: 18,
    requiredSkills: ['Preventive Maintenance', 'Utilities', 'Breakdown Analysis', 'Team Leadership'],
    preferredSkills: ['TPM', 'PLC Troubleshooting', 'Energy Audits'],
    createdAt: '2026-05-11T08:00:00.000Z',
  },
  {
    id: 'job-it-support-lead',
    title: 'IT Support Lead',
    department: 'Information Technology',
    location: 'Pune, Maharashtra',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 1,
    candidatesCount: 11,
    shortlistedCount: 3,
    experienceMin: 5,
    experienceMax: 9,
    requiredSkills: ['IT Service Desk', 'Endpoint Management', 'Network Support', 'Asset Management'],
    preferredSkills: ['Microsoft 365', 'ITIL', 'Plant IT Support'],
    createdAt: '2026-05-12T10:20:00.000Z',
  },
  {
    id: 'job-rd-scientist',
    title: 'R&D Scientist',
    department: 'Research and Development',
    location: 'Hyderabad, Telangana',
    employmentType: 'full_time',
    status: 'open',
    openPositions: 2,
    candidatesCount: 16,
    shortlistedCount: 5,
    experienceMin: 4,
    experienceMax: 8,
    requiredSkills: ['Polymer Chemistry', 'Formulation', 'Lab Trials', 'Technical Documentation'],
    preferredSkills: ['Scale-up Trials', 'Regulatory Testing', 'DOE'],
    createdAt: '2026-05-13T07:55:00.000Z',
  },
  {
    id: 'job-marketing-manager',
    title: 'Marketing Manager',
    department: 'Marketing',
    location: 'Mumbai, Maharashtra',
    employmentType: 'full_time',
    status: 'paused',
    openPositions: 1,
    candidatesCount: 13,
    shortlistedCount: 2,
    experienceMin: 6,
    experienceMax: 10,
    requiredSkills: ['Brand Strategy', 'Trade Marketing', 'Campaign Planning', 'Market Research'],
    preferredSkills: ['B2B Manufacturing', 'Digital Campaigns', 'Agency Management'],
    createdAt: '2026-05-14T05:40:00.000Z',
  },
] satisfies Job[];

export const candidates = [
  {
    id: 'cand-aarya-deshmukh',
    name: 'Aarya Deshmukh',
    email: 'aarya.deshmukh@example.com',
    phone: '+91 98765 12001',
    currentRole: 'Senior Production Engineer',
    currentCompany: 'Pragati Components',
    location: 'Pune, Maharashtra',
    experienceYears: 6,
    skills: [
      { name: 'Lean Manufacturing', years: 5, level: 'expert' },
      { name: 'OEE', years: 4, level: 'proficient' },
      { name: 'Root Cause Analysis', years: 6, level: 'expert' },
    ],
    source: 'employee_referral',
    expectedSalary: 'INR 18 LPA',
    noticePeriod: '45 days',
    matchScore: 92,
    matchReason: 'Strong production engineering background with direct OEE and line-balancing ownership.',
    status: 'active',
    appliedJobId: 'job-production-engineer',
    createdAt: '2026-05-15T08:30:00.000Z',
  },
  {
    id: 'cand-rohan-mehta',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@example.com',
    phone: '+91 98765 12002',
    currentRole: 'Regional Sales Manager',
    currentCompany: 'Axis Industrial Systems',
    location: 'Mumbai, Maharashtra',
    experienceYears: 8,
    skills: [
      { name: 'B2B Sales', years: 8, level: 'expert' },
      { name: 'Dealer Management', years: 6, level: 'expert' },
      { name: 'CRM Forecasting', years: 4, level: 'proficient' },
    ],
    source: 'linkedin',
    expectedSalary: 'INR 28 LPA',
    noticePeriod: '60 days',
    matchScore: 88,
    matchReason: 'Matches B2B sales mandate with strong channel and key-account experience.',
    status: 'active',
    appliedJobId: 'job-sales-manager-b2b',
    createdAt: '2026-05-16T06:20:00.000Z',
  },
  {
    id: 'cand-neha-iyer',
    name: 'Neha Iyer',
    email: 'neha.iyer@example.com',
    phone: '+91 98765 12003',
    currentRole: 'Supply Planning Manager',
    currentCompany: 'Nova Packtech',
    location: 'Bengaluru, Karnataka',
    experienceYears: 9,
    skills: [
      { name: 'Demand Planning', years: 7, level: 'expert' },
      { name: 'S&OP', years: 5, level: 'proficient' },
      { name: 'SAP MM', years: 4, level: 'proficient' },
    ],
    source: 'naukri',
    expectedSalary: 'INR 30 LPA',
    noticePeriod: '30 days',
    matchScore: 84,
    matchReason: 'Strong planning and S&OP experience; location relocation needs confirmation.',
    status: 'on_hold',
    appliedJobId: 'job-supply-chain-lead',
    createdAt: '2026-05-16T12:00:00.000Z',
  },
  {
    id: 'cand-vikram-rao',
    name: 'Vikram Rao',
    email: 'vikram.rao@example.com',
    phone: '+91 98765 12004',
    currentRole: 'Plant Finance Manager',
    currentCompany: 'Kaveri Auto Parts',
    location: 'Bengaluru, Karnataka',
    experienceYears: 12,
    skills: [
      { name: 'Plant Finance', years: 9, level: 'expert' },
      { name: 'Cost Accounting', years: 10, level: 'expert' },
      { name: 'SAP FICO', years: 7, level: 'proficient' },
    ],
    source: 'agency',
    expectedSalary: 'INR 42 LPA',
    noticePeriod: '90 days',
    matchScore: 90,
    matchReason: 'Excellent fit for plant finance control, costing, and audit governance.',
    status: 'active',
    appliedJobId: 'job-finance-controller',
    createdAt: '2026-05-17T09:10:00.000Z',
  },
  {
    id: 'cand-farhan-shaikh',
    name: 'Farhan Shaikh',
    email: 'farhan.shaikh@example.com',
    phone: '+91 98765 12005',
    currentRole: 'Maintenance Manager',
    currentCompany: 'Cosmic Forgings',
    location: 'Aurangabad, Maharashtra',
    experienceYears: 14,
    skills: [
      { name: 'Preventive Maintenance', years: 12, level: 'expert' },
      { name: 'TPM', years: 8, level: 'proficient' },
      { name: 'Utilities', years: 10, level: 'expert' },
    ],
    source: 'walk_in',
    expectedSalary: 'INR 36 LPA',
    noticePeriod: '30 days',
    matchScore: 86,
    matchReason: 'Plant maintenance leadership and utilities experience align closely.',
    status: 'active',
    appliedJobId: 'job-maintenance-head',
    createdAt: '2026-05-18T04:45:00.000Z',
  },
  {
    id: 'cand-kavya-menon',
    name: 'Kavya Menon',
    email: 'kavya.menon@example.com',
    phone: '+91 98765 12006',
    currentRole: 'IT Operations Lead',
    currentCompany: 'Metro Plastics',
    location: 'Pune, Maharashtra',
    experienceYears: 7,
    skills: [
      { name: 'IT Service Desk', years: 7, level: 'expert' },
      { name: 'Microsoft 365', years: 5, level: 'proficient' },
      { name: 'Plant IT Support', years: 3, level: 'working' },
    ],
    source: 'career_site',
    expectedSalary: 'INR 22 LPA',
    noticePeriod: '45 days',
    matchScore: 81,
    matchReason: 'Good IT operations fit with relevant plant support exposure.',
    status: 'active',
    appliedJobId: 'job-it-support-lead',
    createdAt: '2026-05-18T10:15:00.000Z',
  },
  {
    id: 'cand-dr-sameer-kulkarni',
    name: 'Dr. Sameer Kulkarni',
    email: 'sameer.kulkarni@example.com',
    phone: '+91 98765 12007',
    currentRole: 'R&D Chemist',
    currentCompany: 'Helix Materials',
    location: 'Hyderabad, Telangana',
    experienceYears: 6,
    skills: [
      { name: 'Polymer Chemistry', years: 6, level: 'expert' },
      { name: 'Formulation', years: 5, level: 'proficient' },
      { name: 'Lab Trials', years: 6, level: 'expert' },
    ],
    source: 'campus',
    expectedSalary: 'INR 24 LPA',
    noticePeriod: '60 days',
    matchScore: 89,
    matchReason: 'Strong R&D and lab-trial profile for formulation-heavy role.',
    status: 'active',
    appliedJobId: 'job-rd-scientist',
    createdAt: '2026-05-19T07:35:00.000Z',
  },
  {
    id: 'cand-priya-nambiar',
    name: 'Priya Nambiar',
    email: 'priya.nambiar@example.com',
    phone: '+91 98765 12008',
    currentRole: 'Trade Marketing Manager',
    currentCompany: 'Orbit Industrial Brands',
    location: 'Mumbai, Maharashtra',
    experienceYears: 8,
    skills: [
      { name: 'Trade Marketing', years: 7, level: 'expert' },
      { name: 'Campaign Planning', years: 6, level: 'proficient' },
      { name: 'Agency Management', years: 5, level: 'proficient' },
    ],
    source: 'internal',
    expectedSalary: 'INR 31 LPA',
    noticePeriod: '30 days',
    matchScore: 78,
    matchReason: 'Good marketing profile; role is paused pending budget approval.',
    status: 'on_hold',
    appliedJobId: 'job-marketing-manager',
    createdAt: '2026-05-20T06:00:00.000Z',
  },
] satisfies Candidate[];

export const matchScores = candidates.map(candidate => ({
  id: `match-${candidate.id}`,
  jobId: candidate.appliedJobId,
  candidateId: candidate.id,
  overallScore: candidate.matchScore,
  skillScore: Math.min(candidate.matchScore + 2, 98),
  experienceScore: Math.min(candidate.matchScore + 1, 97),
  locationScore: candidate.location.includes('Pune') || candidate.location.includes('Mumbai') ? 92 : 78,
  compensationScore: candidate.expectedSalary.includes('42') ? 74 : 86,
  summary: candidate.matchReason,
  strengths: candidate.skills.slice(0, 2).map(skill => skill.name),
  gaps: candidate.noticePeriod === '90 days' ? ['Long notice period'] : ['Final compensation alignment pending'],
  createdAt: candidate.createdAt,
})) satisfies MatchScore[];

export const screeningSessions = [
  {
    id: 'screening-aarya-deshmukh',
    candidateId: 'cand-aarya-deshmukh',
    jobId: 'job-production-engineer',
    status: 'completed',
    channel: 'phone',
    scheduledAt: '2026-05-21T05:30:00.000Z',
    completedAt: '2026-05-21T06:00:00.000Z',
    summary: 'Confirmed line ownership, shift flexibility, and compensation band.',
    createdAt: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 'screening-rohan-mehta',
    candidateId: 'cand-rohan-mehta',
    jobId: 'job-sales-manager-b2b',
    status: 'in_progress',
    channel: 'video',
    scheduledAt: '2026-05-27T08:00:00.000Z',
    createdAt: '2026-05-25T07:10:00.000Z',
  },
  {
    id: 'screening-neha-iyer',
    candidateId: 'cand-neha-iyer',
    jobId: 'job-supply-chain-lead',
    status: 'queued',
    channel: 'ai_voice',
    scheduledAt: '2026-05-28T06:30:00.000Z',
    createdAt: '2026-05-25T11:45:00.000Z',
  },
] satisfies ScreeningSession[];

export const interviews = [
  {
    id: 'interview-aarya-deshmukh',
    candidateId: 'cand-aarya-deshmukh',
    jobId: 'job-production-engineer',
    status: 'scheduled',
    round: 'technical',
    interviewers: ['Nitin Patil', 'Meera Joshi'],
    scheduledAt: '2026-05-29T05:30:00.000Z',
    feedbackDueAt: '2026-05-29T12:30:00.000Z',
    createdAt: '2026-05-22T04:30:00.000Z',
  },
  {
    id: 'interview-vikram-rao',
    candidateId: 'cand-vikram-rao',
    jobId: 'job-finance-controller',
    status: 'feedback_pending',
    round: 'leadership',
    interviewers: ['Anita Shah', 'Suresh Nair'],
    scheduledAt: '2026-05-26T09:00:00.000Z',
    feedbackDueAt: '2026-05-27T09:00:00.000Z',
    createdAt: '2026-05-23T06:15:00.000Z',
  },
] satisfies Interview[];

export const applications = [
  {
    id: 'app-aarya-deshmukh-production-engineer',
    jobId: 'job-production-engineer',
    candidateId: 'cand-aarya-deshmukh',
    currentStage: 'interview_scheduled',
    status: 'active',
    matchScoreId: 'match-cand-aarya-deshmukh',
    screeningSessionId: 'screening-aarya-deshmukh',
    interviewId: 'interview-aarya-deshmukh',
    createdAt: '2026-05-15T08:30:00.000Z',
    updatedAt: '2026-05-22T04:30:00.000Z',
  },
  {
    id: 'app-rohan-mehta-sales-manager',
    jobId: 'job-sales-manager-b2b',
    candidateId: 'cand-rohan-mehta',
    currentStage: 'screening_pending',
    status: 'active',
    matchScoreId: 'match-cand-rohan-mehta',
    screeningSessionId: 'screening-rohan-mehta',
    createdAt: '2026-05-16T06:20:00.000Z',
    updatedAt: '2026-05-25T07:10:00.000Z',
  },
  {
    id: 'app-neha-iyer-supply-chain-lead',
    jobId: 'job-supply-chain-lead',
    candidateId: 'cand-neha-iyer',
    currentStage: 'ai_matched',
    status: 'on_hold',
    matchScoreId: 'match-cand-neha-iyer',
    screeningSessionId: 'screening-neha-iyer',
    createdAt: '2026-05-16T12:00:00.000Z',
    updatedAt: '2026-05-25T11:45:00.000Z',
  },
  {
    id: 'app-vikram-rao-finance-controller',
    jobId: 'job-finance-controller',
    candidateId: 'cand-vikram-rao',
    currentStage: 'interview_scheduled',
    status: 'active',
    matchScoreId: 'match-cand-vikram-rao',
    interviewId: 'interview-vikram-rao',
    createdAt: '2026-05-17T09:10:00.000Z',
    updatedAt: '2026-05-26T10:00:00.000Z',
  },
  {
    id: 'app-farhan-shaikh-maintenance-head',
    jobId: 'job-maintenance-head',
    candidateId: 'cand-farhan-shaikh',
    currentStage: 'shortlisted',
    status: 'active',
    matchScoreId: 'match-cand-farhan-shaikh',
    createdAt: '2026-05-18T04:45:00.000Z',
    updatedAt: '2026-05-24T08:20:00.000Z',
  },
  {
    id: 'app-kavya-menon-it-support-lead',
    jobId: 'job-it-support-lead',
    candidateId: 'cand-kavya-menon',
    currentStage: 'screened',
    status: 'active',
    matchScoreId: 'match-cand-kavya-menon',
    createdAt: '2026-05-18T10:15:00.000Z',
    updatedAt: '2026-05-23T11:35:00.000Z',
  },
  {
    id: 'app-sameer-kulkarni-rd-scientist',
    jobId: 'job-rd-scientist',
    candidateId: 'cand-dr-sameer-kulkarni',
    currentStage: 'ai_matched',
    status: 'active',
    matchScoreId: 'match-cand-dr-sameer-kulkarni',
    createdAt: '2026-05-19T07:35:00.000Z',
    updatedAt: '2026-05-21T05:25:00.000Z',
  },
  {
    id: 'app-priya-nambiar-marketing-manager',
    jobId: 'job-marketing-manager',
    candidateId: 'cand-priya-nambiar',
    currentStage: 'sourced',
    status: 'on_hold',
    matchScoreId: 'match-cand-priya-nambiar',
    createdAt: '2026-05-20T06:00:00.000Z',
    updatedAt: '2026-05-20T06:00:00.000Z',
  },
] satisfies Application[];

export const recruiterAlerts = [
  {
    id: 'alert-feedback-overdue',
    title: 'Interview feedback pending',
    description: 'Finance Controller leadership feedback is due today.',
    severity: 'warning',
    relatedJobId: 'job-finance-controller',
    relatedCandidateId: 'cand-vikram-rao',
    createdAt: '2026-05-27T03:30:00.000Z',
  },
  {
    id: 'alert-high-match-production',
    title: 'High match ready for interview',
    description: 'Aarya Deshmukh has a 92% match for Production Engineer.',
    severity: 'info',
    relatedJobId: 'job-production-engineer',
    relatedCandidateId: 'cand-aarya-deshmukh',
    createdAt: '2026-05-22T04:30:00.000Z',
  },
  {
    id: 'alert-paused-marketing-role',
    title: 'Paused job has active candidates',
    description: 'Marketing Manager has candidates on hold while budget approval is pending.',
    severity: 'critical',
    relatedJobId: 'job-marketing-manager',
    createdAt: '2026-05-24T10:00:00.000Z',
  },
] satisfies RecruiterAlert[];
